[package]
name = "hello-rust"
version = "0.1.0"
authors = ["Lanzhi <lanzhi_lee@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
